version: '3.4'

services:
  db:
    image: rest-api-with-aspnet-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: API/RESTAPIWithASPNET/Database/Docker/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: restapi_with_aspnet
    ports:
      - 3308:3306
    networks:
      - udemy-network

  rest-api-with-aspnet:
    image: rest-api-with-aspnet
    build:
      context: .
      dockerfile: API/RESTAPIWithASPNET/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:8081
      - 4430:8080
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge